name: PR Validation

on:
  pull_request:
    paths:
      - '**.md'

jobs:
  build_and_verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: |
          echo '${{ toJSON(github.event) }}'
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'

          echo '${{ steps.file_changes.outputs.files_modified}}' | jq 'map(select(.|test("\\.md")))' 
      - run: |
          gh workflow run manual.yml -f os=Unix
          gh run list --workflow=manual.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      # - name: Invoke workflow without inputs
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: Manual
      #     token: ${{ secrets.PAT }}
